apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  #type: NodePort  
  type: LoadBalancer
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - name: agent
      port: 50000
      targetPort: 50000
