apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.service_name }}
  # namespace: {{ .Values.namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetport }}
      # nodePort: {{ .Values.service.nodeport }}
  selector:
    app: {{ .Values.deployment.pod_label }}
